spring:
  application:
    name: auth-service

server:
  port: 3201

keycloak:
  auth-server-url: http://localhost:5052
  realm: buyers_realm
  clientId: spring
  adminClientId: admin-cli
  credentials:
    username: admin
    password: admin
    adminSecret: 7JLOvVVCyvWqX8l3XOOFzxabmRmbmlof
    secret: ICbjD4csW4FwZxy3MH5Bmz56kHKDoPgA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
    enabled: true

domain: http://localhost