spring:
  application:
    name: auth-service

server:
  port: 3201

keycloak:
  auth-server-url: http://localhost:5052
  realm: buyers_realm
  clientId: springsecurity
  adminClientId: admin-cli
  credentials:
    adminSecret: bA27Tt7jfWoeS7PUJVQzSrxwAGe4vSI7
    secret: 63B0GkzMnnw7VgYsVqapaWrwOzKgXmRF