spring:
  application:
    name: auth-service

server:
  port: 3201

keycloak:
  auth-server-url: http://localhost:5052
  realm: buyers_realm
  clientId: springsecurity
  adminClientId: admin-cli
  credentials:
    adminSecret: bA27Tt7jfWoeS7PUJVQzSrxwAGe4vSI7
    secret: 63B0GkzMnnw7VgYsVqapaWrwOzKgXmRF
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
    enabled: true