spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-route
          uri: lb://user-service/
          predicates:
            - Path=/api/v1/users/**
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: product-service-route-categories
          uri: lb://product-service
          predicates:
            - Path=/api/v1/categories/**
        - id: product-service-route-reviews
          uri: lb://product-service
          predicates:
            - Path=/api/v1/reviews/**
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: elastic-service-route
          uri: lb://elastic-service
          predicates:
            - Path=/api/v1/search/**
        - id: media-store-route
          uri: lb://media-store
          predicates:
            - Path=/api/v1/media/**
        - id: websocket-route
          uri: lb://websocket-service
          predicates:
            - Path=/api/v1/websocket/**
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka