spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5051/users
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
    enabled: true

keycloak:
  auth-server-url: http://localhost:5052/
  realm: buyers-realm
  clientId: admin-cli
  credentials:
    secret: bA27Tt7jfWoeS7PUJVQzSrxwAGe4vSI7
