spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5051/products
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5052/realms/buyers_realm
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
    enabled: true
domain: http:localhost