spring:
  application:
    name: media-store
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    fetch-registry: true
    register-with-eureka: true
    enabled: true